// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © GGamer314

//@version=4
strategy("SPY Trading Bot", overlay=true)


longSignal(price) => 
    fast = 12, slow = 26
    fastMA = ema(price, fast)
    slowMA = ema(price, slow)
    macd = fastMA - slowMA
    signal = sma(macd, 9)
    macdCrossover = if macd > signal
        true
    else
        false
        
    stochasticEntrySignal = false
        
    smoothK = input(14, minval=1), smoothD = input(3, minval=1)
    k = sma(stoch(close, high, low, smoothK), 3)
    d = sma(k, smoothD)
    
    if(d < 20)
        if(k > d)
            stochasticEntrySignal := true
    
    entrySignal = false
    
    if(macdCrossover)
        if(stochasticEntrySignal)
            entrySignal := true
    entrySignal
    
shortSignal(price) => 
    
    //smaCrossunder = crossunder(sma(price, ema1), sma(price, ema2))
    
    fast = 12, slow = 26
    fastMA = ema(price, fast)
    slowMA = ema(price, slow)
    macd = fastMA - slowMA
    signal = sma(macd, 9)
    macdCrossunder = if macd < signal
        true
    else
        false
        
    stochasticExitSignal = false
        
    smoothK = input(14, minval=1), smoothD = input(3, minval=1)
    k = sma(stoch(close, high, low, smoothK), 3)
    d = sma(k, smoothD)
    
    if(d > 80)
        if(k < d)
            stochasticExitSignal := true
    
    exitSignal = false
    
    if(macdCrossunder)
        if(stochasticExitSignal)
            exitSignal := true
    exitSignal
        
    
longCondition = longSignal(close)
if (longCondition)
    strategy.entry("My Long Entry Id", strategy.long)

shortCondition = shortSignal(close)
if (shortCondition)
    strategy.entry("My Short Entry Id", strategy.short)
